[package]
name = "techincal_2"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
reqwest = {version = "0.12.12",features = ["json"]}
tokio = {version = "1.43.0",features = ["full"]}
serde_json = "1.0"
